# Generated by Django 2.0.2 on 2018-06-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180613_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'OpenStack'), (4, 'GoLang'), (5, '其他')], default=None),
        ),
        migrations.AlterField(
            model_name='updown',
            name='up',
            field=models.NullBooleanField(verbose_name='是否赞'),
        ),
    ]
